Creando validacion
ArquiTech-App/backend-arquitech pull request #10
Opened 2022-04-12 21:32 UTC by Deveckor

2022-04-12 21:55 UTC, KristomeisterDev approved these changes

2022-04-13 00:51 UTC, EveFer requested changes

2022-04-13 00:51 UTC, EveFer commented on src/Middlewares/validation.js
> +        if (idReq != idToken) throw new Error(
@Deveckor Hay que utilizar la validación `!==`
```suggestion
        if (idReq !== idToken) throw new Error(
```

2022-04-13 03:26 UTC, EveFer approved these changes

2022-04-13 03:27 UTC, merged