CRUDoffice
ArquiTech-App/backend-arquitech pull request #2
Opened 2022-03-25 01:20 UTC by KristomeisterDev

se sube CRUD de office

2022-03-26 01:44 UTC, EveFer commented on src/UseCases/office.js
> +    const officeFound = await Office.findOne({office: office})
@KristomeisterDev. Lo ideal es buscar por email, ya que todos los despachos tendrán un email único

2022-03-26 01:45 UTC, EveFer requested changes

2022-03-26 01:45 UTC, EveFer commented on src/UseCases/office.js
> +    return Office.create({name, address, email, password: passwordEncrypt, rfc, clients, residents, projects})
```suggestion
    return Office.create({...dataOffice password: passwordEncrypt}) 
```

Con spread operator se ahorran el pasar todas las propiedades al crear la office 🙃.  @KristomeisterDev

2022-03-26 03:20 UTC, KristomeisterDev commented on src/UseCases/office.js
> +    return Office.create({name, address, email, password: passwordEncrypt, rfc, clients, residents, projects})
muy cierto Fer, era lo que hacíamos con populate en la practica, no se me ocurrió pero muchas gracias no me vuelve a fallar

2022-03-26 03:20 UTC, KristomeisterDev commented on src/UseCases/office.js
> +    const officeFound = await Office.findOne({office: office})
listo, nada mas subo los cambios

2022-03-26 03:27 UTC, EveFer requested changes

2022-03-26 03:27 UTC, EveFer commented on src/UseCases/office.js
> +    const emailFound = await Office.findOne({office: email})
```suggestion
    const emailFound = await Office.findOne({email: email})
```

Para que busque por el email abusados con esta parte. @KristomeisterDev

2022-03-26 03:31 UTC, KristomeisterDev commented on src/UseCases/office.js
> +    const emailFound = await Office.findOne({office: email})
estaba seguro que era office: email alo mejor como estoy en clase zoom me consume mucho y luego me salen errores

2022-03-26 03:32 UTC, KristomeisterDev commented on src/UseCases/office.js
> +    const emailFound = await Office.findOne({office: email})
ah, ya vi perdón le entendí mal.

2022-03-26 03:33 UTC, KristomeisterDev commented on src/UseCases/office.js
> +    const emailFound = await Office.findOne({office: email})
ya quedo Fer

2022-03-26 04:56 UTC, EveFer approved these changes

2022-03-31 04:33 UTC, Deveckor approved these changes

2022-03-31 04:34 UTC, merged